"use client";

import { z } from "zod";
import { useEffect, useRef, useState } from "react";
import { usePanelFocus } from "../hooks/usePanelFocus";
import { BookmarkActionFeedback } from "./BookmarkActionFeedback";
import { Bookmark, type BookmarkFeedback } from "../hooks/useBookmarksList";
import { InspectorHeader } from "./inspector/InspectorHeader";
import { MetadataGrid } from "./inspector/MetadataGrid";
import { ActionButtons } from "./inspector/ActionButtons";
import { readCapturedSource } from "@/lib/capture-contract";
import { Linkify } from "./Linkify";

const provenanceSchema = z.object({ version: z.literal(1), model: z.string(), method: z.string(), captureStatus: z.string() });
function generationLabel(json: string | null | undefined) { try { const parsed = provenanceSchema.safeParse(JSON.parse(json ?? "null")); return parsed.success ? `Generated by ${parsed.data.model} from ${parsed.data.method} (${parsed.data.captureStatus})` : "Saved summary; provenance unavailable"; } catch { return "Saved summary; provenance unavailable"; } }

type Props = {
  selected: Bookmark | null; translatedText: string | null; isTranslating: boolean; busyId: string | null;
  onTranslate: (id: string) => void; onReprocess: (id: string, replaceEdited?: boolean) => void; onEdit: (bookmark: Bookmark) => void;
  feedback?: BookmarkFeedback[]; suspended?: boolean; reading?: boolean; onToggleRead: (bookmark: Bookmark) => void;
  onClose: () => void; getYouTubeTitle: (bookmark: Bookmark) => string | null;
};

export function BookmarkInspector({ selected, translatedText, isTranslating, busyId, onTranslate, onReprocess, onEdit, onClose, getYouTubeTitle, feedback = [], suspended = false, reading = false, onToggleRead }: Props) {
  const panel = useRef<HTMLElement>(null);
  const [narrow, setNarrow] = useState(false);
  useEffect(() => { const query = window.matchMedia("(max-width: 1279px)"); const update = () => setNarrow(query.matches); update(); query.addEventListener("change", update); return () => query.removeEventListener("change", update); }, []);
  usePanelFocus(panel, Boolean(selected) && !suspended, narrow, selected?.id ?? null, onClose);
  if (!selected) return <aside className="rounded-lg bg-surface-container p-4"><p className="text-sm text-on-surface-variant">Select a bookmark to inspect it.</p></aside>;

  const capture = readCapturedSource(selected.captureJson);
  return (
    <aside ref={panel} tabIndex={-1} role={narrow ? "dialog" : "region"} aria-modal={narrow || undefined} aria-label="Bookmark reader" className="fixed inset-y-0 right-0 z-40 w-full max-w-[440px] overflow-y-auto border-l border-outline-variant bg-surface-container p-4 shadow-xl break-words xl:relative xl:z-auto xl:w-auto xl:max-w-none xl:rounded-lg xl:border xl:shadow-none">
      <div className="flex flex-col gap-5">
        <InspectorHeader source={selected.source} title={selected.source === "yt" ? getYouTubeTitle(selected) : "Bookmark"} category={selected.category} folderName={selected.folderName} onClose={onClose} />
        <BookmarkActionFeedback feedback={feedback} />
        <MetadataGrid b={selected} />
        {selected.summary && <p className="text-sm text-on-surface-variant">Summary source: {selected.editedAt ? "Human correction" : generationLabel(selected.summarySource)}.</p>}
        {capture && <p className="text-sm text-on-surface-variant">Source: {capture.method}, {capture.capture.status}{capture.language ? `, ${capture.language}` : ""}. Captured {new Date(capture.capture.capturedAt).toLocaleString()}. {capture.capture.reason}</p>}
        {selected.availability && selected.availability !== "available" && <p className="text-sm text-on-surface-variant">Video availability: {selected.availability}. Previously saved content remains readable.</p>}
        <section>
          <h3 className="text-sm font-semibold">{selected.source === "yt" ? "Digest" : "Summary"}</h3>
          <div className="mt-2 rounded-md bg-surface-container-lowest p-3 text-sm leading-6 whitespace-pre-wrap">
            <Linkify text={selected.summary || "No summary yet."} />
          </div>
        </section>
        <section>
          <h3 className="text-sm font-semibold">Original text</h3>
          <div className="mt-2 max-h-72 overflow-auto rounded-md bg-surface-container-lowest p-3 text-sm leading-6 whitespace-pre-wrap">
            <Linkify text={selected.text || "No text."} />
          </div>
        </section>
        {translatedText && (
          <section>
            <h3 className="text-sm font-semibold">Translation</h3>
            <div className="mt-2 max-h-72 overflow-auto rounded-md bg-surface-container-lowest border border-primary/20 p-3 text-sm leading-6 whitespace-pre-wrap">
              <Linkify text={translatedText} />
            </div>
          </section>
        )}
        {capture && capture.capture.sections.length > 0 && <details className="rounded-md bg-surface-container-lowest p-3">
          <summary className="cursor-pointer text-sm font-semibold">Captured source passages</summary>
          <div className="mt-2 max-h-80 overflow-auto space-y-3 text-sm leading-6">
            {capture.capture.sections.map((section, index) => <p key={index}>
              {section.startSeconds !== null && selected.source === "yt" && <a className="mr-2 text-primary underline" target="_blank" rel="noreferrer" href={`${selected.tweetUrl}${selected.tweetUrl.includes("?") ? "&" : "?"}t=${Math.floor(section.startSeconds)}`}>
                {Math.floor(section.startSeconds / 60)}:{String(Math.floor(section.startSeconds % 60)).padStart(2, "0")}
              </a>}
              {section.text}
            </p>)}
          </div>
        </details>}
        {selected.tags && <section><h3 className="text-sm font-semibold">Tags</h3><div className="mt-2 flex flex-wrap gap-2">{selected.tags.split(",").map(t => <span key={t} className="rounded bg-surface-container-high px-2 py-1 text-xs font-semibold">{t.trim()}</span>)}</div></section>}
        <ActionButtons b={selected} busy={busyId === selected.id} translating={isTranslating} onReprocess={onReprocess} onEdit={onEdit} onTranslate={onTranslate} reading={reading} onToggleRead={onToggleRead} />
      </div>
    </aside>
  );
}
